"""esquema inicial

Revision ID: 874b40c0d142
Revises: 
Create Date: 2026-06-18 19:25:36.532958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '874b40c0d142'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_category'), 'technologies', ['category'], unique=False)
    op.create_index(op.f('ix_technologies_id'), 'technologies', ['id'], unique=False)
    op.create_index(op.f('ix_technologies_name'), 'technologies', ['name'], unique=True)
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=260), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('source_url', sa.String(length=800), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('modality', sa.String(length=50), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('collected_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_category'), 'job_postings', ['category'], unique=False)
    op.create_index(op.f('ix_job_postings_city'), 'job_postings', ['city'], unique=False)
    op.create_index(op.f('ix_job_postings_collected_at'), 'job_postings', ['collected_at'], unique=False)
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.create_index(op.f('ix_job_postings_modality'), 'job_postings', ['modality'], unique=False)
    op.create_index(op.f('ix_job_postings_published_at'), 'job_postings', ['published_at'], unique=False)
    op.create_index(op.f('ix_job_postings_region'), 'job_postings', ['region'], unique=False)
    op.create_index(op.f('ix_job_postings_seniority'), 'job_postings', ['seniority'], unique=False)
    op.create_index(op.f('ix_job_postings_source'), 'job_postings', ['source'], unique=False)
    op.create_index(op.f('ix_job_postings_source_url'), 'job_postings', ['source_url'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_table('job_posting_technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=False),
    sa.Column('technology_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_posting_id', 'technology_id', name='uq_job_technology')
    )
    op.create_index(op.f('ix_job_posting_technologies_id'), 'job_posting_technologies', ['id'], unique=False)
    op.create_index(op.f('ix_job_posting_technologies_job_posting_id'), 'job_posting_technologies', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_job_posting_technologies_technology_id'), 'job_posting_technologies', ['technology_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_posting_technologies_technology_id'), table_name='job_posting_technologies')
    op.drop_index(op.f('ix_job_posting_technologies_job_posting_id'), table_name='job_posting_technologies')
    op.drop_index(op.f('ix_job_posting_technologies_id'), table_name='job_posting_technologies')
    op.drop_table('job_posting_technologies')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source_url'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_source'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_seniority'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_region'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_published_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_modality'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_collected_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_city'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_category'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_technologies_name'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_id'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_category'), table_name='technologies')
    op.drop_table('technologies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
